apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: svc-central
spec:
 cidr: 10.101.0.0/16
 natOutgoing: false
 disabled: true
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: pod-central
spec:
 cidr: 10.240.0.0/16
 natOutgoing: false
 disabled: true
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: svc-dc1
spec:
 cidr: 10.111.0.0/16
 natOutgoing: false
 disabled: true
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: pod-dc1
spec:
 cidr: 10.241.0.0/16
 natOutgoing: false
 disabled: true