kind: Cluster
name: central
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    listenAddress: 127.0.0.1
    protocol: TCP
- role: worker
networking:
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.110.0.0/16"
  disableDefaultCNI: true