kind: Cluster
name: dc1
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
networking:
  podSubnet: "10.241.0.0/16"
  serviceSubnet: "10.111.0.0/16"
  disableDefaultCNI: true